### ISSUE TITLE
Not working in Opera GX

### ISSUE THREAD

**Issue by Exioncore** [borsini/chrome-otto-tabs#5]
As per title, the extension currently does not work in Opera GX. As a minor thing also the popup menu coloring is broken (Really dark background with black text so not very readable). More specifically the second tab selector never appears and tabs are never grouped together. (I'm used to using the extension in Vivaldi but recently wanted to try Opera GX however not having this extension working on it would be kind of a deal break for me)

Looking at the debug output of the extension it seems to be working properly but the tabs end up never being actually grouped in the UI itself.

Would be great if it could be fixed.

**Comment by borsini** [comment]
Hello there. I tried Opera GX and there is no standard tab grouping support. They seem to rely on [workspaces](https://www.opera.com/fr/features/workspaces) to do this job. 
It's curious because on classic Opera the grouping feature is present 🤷 

Regarding the dark background, I fixed this by adding a white one. That fix will ship in next version.
